### ISSUE TITLE
Can not resolve installation with typescript-eslint 6.0.0

### ISSUE THREAD

**Issue by ElPrudi** [a-tarasyuk/eslint-plugin-redundant-undefined#2]
typescript-eslint/parser version 6.0.0 released a couple of days ago and this plugin can not resolve this version. Could you please update your dependencies?

**Comment by a-tarasyuk** [comment]
@ElPrudi I've published a new version supporting `ts-eslint 6.*.`

**Comment by ElPrudi** [comment]
Can confirm. No more npm errors. Thank you very much :)
